# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank
theme: jekyll-theme-minimal